### ISSUE TITLE
Issue with Multiple Lists example.

### ISSUE THREAD

**Issue by ivanjeremic** [thisbeyond/solid-dnd#48] opened 2022-06-08 17:01 UTC
I need to work with multiple lists in my project so I started out by copy pasting the Multiple List example from the website in my CodeSanbox to get familiar with it, the code in untouched I really changed nothing except added some inline styles for better visibility.

The issue is that the dnd is not working properly, dragging items from one to the other Column is working mostly only the first time and dragging all in to one almost never and generally it stops working properly after first drag. I'm confused and asking myself now is this really an issue with the way I try to test this maybe a style issue, or maybe something with example itself?

[https://codesandbox.io/s/solid-multiple-dnd-4b7n4l?file=/src/main.tsx](https://codesandbox.io/s/solid-multiple-dnd-4b7n4l?file=/src/main.tsx)

**Comment by MarvinRudolph** [comment] 2022-06-10 07:18
Yeah I can confirm that it's an issue, even with the original styles see here https://stackblitz.com/edit/vitejs-vite-mgwbtc?file=src/App.tsx.

**Comment by ivanjeremic** [comment] 2022-07-23 16:15
> Yep - this started being an issue with the move from solid-js `1.3.17` to `1.4.x`. 

Will this be fixed in the rewrite of this library or can we expect some bugfix for it sooner?

**Comment by martinpengellyphillips** [comment] 2022-07-26 11:39
I think as part of the refactor (not rewrite!) is more realistic expectation. But if someone wants to propose a pr with a fix for current version then I'll happily review it for merge and release.

**Comment by Zachiah** [comment] 2022-09-07 15:06
Hi @martinpengellyphillips Is there any kind of a timeline for when this should be fixed, or is this being worked on? My team would work on fixing it as we are using solid-dnd, and our drag-and-drop is broken in some places because of this issue. Thanks!

**Comment by martinpengellyphillips** [comment] 2022-09-07 16:41
I've got a working local branch with SolidJS 1.5 and I'd expect to release that in the next week alongside other changes.

**Comment by martinpengellyphillips** [comment] 2022-09-07 21:16
This is now addressed in [0.7.0](https://github.com/thisbeyond/solid-dnd/releases/tag/0.7.0) which now supports Solid JS 1.5+

**Closed by martinpengellyphillips** 2022-09-07 21:16 UTC
Labels: bug
